# OpenVPN Sunucu Konfigürasyonu
port 4444
proto udp
dev tun

# Fichiers de certificats
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh.pem
tls-auth /etc/openvpn/easy-rsa/ta.key 0

# Reseau VPN
server 10.8.0.0 255.255.255.0

# Paramètres du client
ifconfig-pool-persist ipp.txt
client-to-client

# Accès au réseau interne (192.168.15.0/24)
push "route 192.168.15.0 255.255.255.0"

# DNS serveurs
push "dhcp-option DNS 192.168.15.253"
push "dhcp-option DNS 192.168.15.252"
push "dhcp-option DOMAIN linuxisgood.local"

# Security
cipher AES-256-CBC
auth SHA256
tls-version-min 1.2

# Users
user nobody
group nogroup

# Connection Configuration
keepalive 10 120
persist-key
persist-tun

# Log
status openvpn-status.log
log-append /var/log/openvpn.log
verb 3
